name: Pipeline CD WordPress

on:
  push:
    paths:
      - 'docker-compose.yml'
      - '.github/workflows/deploy.yml'
  workflow_dispatch:

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar SSH
        run: |

          mkdir -p ~/.ssh

          echo "${{ secrets.OCI_VM_SSH_KEY }}" > ~/.ssh/id_rsa

          chmod 600 ~/.ssh/id_rsa

      - name: Copiar docker-compose
        run: |

          scp \
          -o StrictHostKeyChecking=no \
          docker-compose.yml \
          ${{ secrets.OCI_VM_USER }}@${{ secrets.OCI_VM_HOST }}:/home/ubuntu/

      - name: Deploy
        run: |
            ssh -o StrictHostKeyChecking=no \
            ${{ secrets.OCI_VM_USER }}@${{ secrets.OCI_VM_HOST }} << EOF

            cat > /home/ubuntu/.env << EOL
            MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
            MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}
            MYSQL_USER=${{ secrets.MYSQL_USER }}
            MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
            EOL

            cd /home/ubuntu

            docker compose down --remove-orphans || true
            sudo docker compose up -d

            EOF